OPENAI_API_KEY = "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"
EMAIL = "samuelomajali2017@mail.com"
EMAIL_PASSWORD = "xxad rcxu ymjr rqfw"